Feature/frontend/react router
dominieq/rule-studio pull request #82
Opened 2020-10-05 21:45 UTC by emsi-iggy

2020-10-06 19:23 UTC, tomdziwood approved these changes

2020-10-06 20:26 UTC, tomdziwood requested changes
File "package.json" is weird.

2020-10-07 18:09 UTC, dominieq requested changes

2020-10-07 18:09 UTC, dominieq commented on src/main/frontend/src/App/App.js
> +        const urlSplitted = url.split('/');
Add empty line between variable declarations and logic.

2020-10-13 20:58 UTC, emsi-iggy commented on src/main/frontend/src/App/App.js
> +        const urlSplitted = url.split('/');
[solved in this commit](https://github.com/dominieq/rule-studio/pull/82/commits/d35c1812970d19212880a0f672fe77145fa75d76)

2020-12-23 09:59 UTC, dominieq approved these changes

2020-12-23 11:17 UTC, tomdziwood approved these changes

2020-12-23 11:54 UTC, dominieq commented
Fixes #83

2020-12-23 11:55 UTC, merged